#!/bin/sh
set -e

if [ "$#" -ne 2 ]; then
    echo "Usage: ${0} [raylib|web] source.c"
    exit 1
fi

BACKEND="${1}"
SOURCE="${2}"
SUFFIX="${SOURCE##*.}"
OUTPUT="${SOURCE}.${BACKEND}"
if [ -z "${SAGE_HOME}" ]; then
    SAGE_HOME="$(pwd)"
fi

if [ "${SUFFIX}" = 'c' -a "${BACKEND}" = 'raylib' ]; then
    cc $("${SAGE_HOME}/sage-config" "${BACKEND}") -o "${OUTPUT}.out" \
        "${SAGE_HOME}/sage-${BACKEND}.c" "${SOURCE}"
elif [ "${SUFFIX}" = 'c' -a "${BACKEND}" = 'web' ]; then
    emcc $("${SAGE_HOME}/sage-config" "${BACKEND}") -o "${OUTPUT}.html" \
        "${SAGE_HOME}/sage-${BACKEND}.c" "${SOURCE}"
elif [ "${SUFFIX}" = 'sunder' -a "${BACKEND}" = 'raylib' ]; then
    SUNDER_CFLAGS="$(${SAGE_HOME}/sage-config ${BACKEND})" \
    SUNDER_SEARCH_PATH="${SUNDER_SEARCH_PATH}:${SAGE_HOME}" \
    sunder-compile -o "${OUTPUT}.out" "sage-${BACKEND}.c" "${SOURCE}"
elif [ "${SUFFIX}" = 'sunder' -a "${BACKEND}" = 'web' ]; then
    SUNDER_CC=emcc \
    SUNDER_ARCH=wasm32 \
    SUNDER_HOST=emscripten \
    SUNDER_CFLAGS="$(${SAGE_HOME}/sage-config ${BACKEND})" \
    SUNDER_SEARCH_PATH="${SUNDER_SEARCH_PATH}:${SAGE_HOME}" \
    sunder-compile -o "${OUTPUT}.html" "sage-${BACKEND}.c" "${SOURCE}"
else
    echo 'error: unknown configuration'
    exit 1
fi
